// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/download": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/commands": {
    params: {};
  };
  "/commands/:name": {
    params: {
      "name": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/download" | "/features" | "/about" | "/commands" | "/commands/:name";
  };
  "layout.tsx": {
    id: "layout";
    page: "/" | "/download" | "/features" | "/about" | "/commands" | "/commands/:name";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/download.tsx": {
    id: "routes/download";
    page: "/download";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/commands.tsx": {
    id: "routes/commands";
    page: "/commands";
  };
  "routes/command-detail.tsx": {
    id: "routes/command-detail";
    page: "/commands/:name";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layout": typeof import("./src/app/layout.tsx");
  "routes/home": typeof import("./src/app/routes/home.tsx");
  "routes/download": typeof import("./src/app/routes/download.tsx");
  "routes/features": typeof import("./src/app/routes/features.tsx");
  "routes/about": typeof import("./src/app/routes/about.tsx");
  "routes/commands": typeof import("./src/app/routes/commands.tsx");
  "routes/command-detail": typeof import("./src/app/routes/command-detail.tsx");
};