// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/download": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/commands": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/download" | "/about" | "/docs" | "/docs/:slug" | "/commands";
  };
  "layout.tsx": {
    id: "layout";
    page: "/" | "/download" | "/about" | "/docs" | "/docs/:slug" | "/commands";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/download.tsx": {
    id: "routes/download";
    page: "/download";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/docs-detail.tsx": {
    id: "routes/docs-detail";
    page: "/docs/:slug";
  };
  "routes/commands.tsx": {
    id: "routes/commands";
    page: "/commands";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layout": typeof import("./src/app/layout.tsx");
  "routes/home": typeof import("./src/app/routes/home.tsx");
  "routes/download": typeof import("./src/app/routes/download.tsx");
  "routes/about": typeof import("./src/app/routes/about.tsx");
  "routes/docs": typeof import("./src/app/routes/docs.tsx");
  "routes/docs-detail": typeof import("./src/app/routes/docs-detail.tsx");
  "routes/commands": typeof import("./src/app/routes/commands.tsx");
};