import type { I18nDictionary } from "./types";
export const en: I18nDictionary = {
  nav: { product: "Product", showcase: "App tour", assembly: "Assembly", download: "Download", skill: "Download Skill", language: "切换为简体中文", menu: "Open navigation", close: "Close navigation", skip: "Skip to content" },
  hero: { eyebrow: "BUILT FOR COUNTER-STRIKE 2", title: "Your config.", highlight: "Your home ground.", description: "From a CFG file to a complete workspace. Manage presets, combine features and tune video in the app, or let your agent help through the srpcfg CLI and skill.", download: "Get SrP-CFG", explore: "See it in action", platform: "Windows 10 / 11 · x64 · Open source", floatingLabel: "Actual app interface", scroll: "Explore below" },
  showcase: { eyebrow: "MEET YOUR WORKSPACE", title: "Your config, in focus.", description: "One desktop workspace for Steam, game files and personal preferences. Explore how the pages work together.", previous: "Previous page", next: "Next page", actual: "Actual app screenshots", screens: [
    { id: "overview", title: "Start with an overview", short: "Overview", description: "Locate Steam and CS2, choose the current account and inspect your SrP-CFG installation.", points: ["Paths and accounts in one place", "Packages update independently of the app", "Mount autoexec without replacing user content"] },
    { id: "presets", title: "Find your starting point", short: "Presets", description: "Load a preset, then edit settings, keymaps and custom.cfg in the same workspace.", points: ["File differences and unsaved drafts marked separately", "Syntax colors, line numbers and font zoom", "Back up game files before saving changes"] },
    { id: "assembly", title: "Build your own loadout", short: "Assembly", description: "Baseline, features, mode launchers and personal config share a continuous workspace with a fixed editor.", points: ["Optional default keymaps for features", "Launch modes with a chosen key", "Keep personal overrides and unsaved drafts"] },
    { id: "video", title: "Picture your settings", short: "Video", description: "Form controls and the text editor share one draft. Save a staging copy, then apply it to the current account.", points: ["Preserve hardware IDs and unknown fields", "Pause application while CS2 is running", "Reset staged defaults without changing game files"] },
    { id: "annotations", title: "Give practice a guide", short: "Map guides", description: "Select maps to deploy, inspect or remove their guides, while keeping personal annotations.", points: ["Multiple map guides can coexist", "Action scope is separate from installation status", "Discover new guides through package catalogs"] },
  ] },
  features: { eyebrow: "DESIGNED FOR YOUR CONFIG", title: "Stay in control of every change.", description: "The app, CLI and agent skill share a configuration core. Files, launch entries and versions stay visible, with room to customize.", items: [
    { title: "Native files. Readable changes.", description: "Works through CS2 config files and entry commands. Inspect and edit the content that actually gets written.", tag: "CFG / VCFG / KV3" },
    { title: "Stage first. Apply next.", description: "Package originals and working copies stay separate. Updates preserve edited copies and never deploy automatically.", tag: "Independent versions · Working copies" },
    { title: "Keep your work. Keep a backup.", description: "Protect unsaved drafts and back up files before writing. Unchanged content does not create redundant backups.", tag: "Up to 20 distinct-content revisions" },
    { title: "Let your agent help configure.", description: "Install srpcfg-skill to guide your agent through diagnostics, presets and assembly via the CLI. Staging and deployment stay distinct, and binding conflicts require your decision.", tag: "srpcfg CLI · Agent Skill" },
  ] },
  assembly: { eyebrow: "BUILD YOUR OWN LOADOUT", title: "Unpack the features.", highlight: "Keep the choices.", description: "Your custom.cfg holds the entry points. Pick features, assign mode launch keys and put personal preferences last.", layers: [
    { title: "Valve baseline", description: "Choose settings and keymaps separately. Applying the baseline removes preset entries, preserving your personal layer." },
    { title: "Feature modules", description: "Combine AutoView, crosshair/view, Knife, Zeus and more. Include default keys only when you want them." },
    { title: "Mode launchers", description: "Practice, preview and Demo start from a bound key. Multiple entries coexist, with confirmation before conflicts." },
    { title: "Personal overrides", description: "user/custom.cfg comes last. Your sensitivity, bindings and preferences remain your choice." },
  ], expand: "Expand layers", collapse: "Collapse layers", note: "Interactive configuration diagram. Explore the layers; no game commands are executed.", codeLabel: "Example launch entries", diagram: "Interactive configuration layers", modeHint: "The bound key launches the mode" },
  workflow: { title: "Three steps to your next match.", steps: [
    { title: "Download & prepare", description: "Choose the installer or portable build. Offline configs are included; the app detects your game and account." },
    { title: "Choose & customize", description: "Start with a preset or assemble your own features. Edit a working copy, review and save." },
    { title: "Apply & play", description: "Deploy to the right location. CFG entries run at the next launch or after srp_reload." },
  ] },
  downloads: { eyebrow: "READY WHEN YOU ARE", title: "Your next match starts here.", description: "Get the desktop app, independent config packages, or srpcfg-skill for your agent. Choose the way you work.", app: "SrP-CFG desktop app", appNote: "Windows x64 · Offline configs and srpcfg CLI included", setup: "Setup installer", setupNote: "For everyday use. The installer manages program files.", portable: "Portable ZIP", portableNote: "Extract and run. No installation required.", packages: "Config packages & agent skill", packageNote: "Three game config packages and one CLI skill, released independently.", source: "Software download source", mirror: "Accelerated · Default", direct: "GitHub direct", sourceNote: "Mirror: gh.269601.xyz. Switching sources updates the software download links.", loading: "Loading the latest release…", unavailable: "Release info is unavailable. Switch sources, retry, or visit Releases.", noRelease: "No official software release with ZIP / Setup was found. Visit Releases for available files.", retry: "Refresh", releases: "View Releases", download: "Download", latest: "Latest", size: "Size", hash: "Copy SHA-256", copied: "Checksum copied", copyFailed: "Copy failed; select the checksum manually", packageSource: "Configs and the skill come from this site's Cloudflare download store. Switching software sources does not change these links.", srp: "Runtime, presets and assembly modules with a personal override layer.", video: "Video parameter template. Check resolution and display mode before applying.", annotations: "Map-specific annotation guides. Keep your personal mapguide intact.", skill: "Guide your agent through CS2 diagnostics, assembly and configuration using srpcfg, with explicit scopes and conflict decisions.", skillInstall: "Extract the ZIP and place srpcfg-skill in your agent's skills directory. Contains skill files only; install the srpcfg CLI before use.", skillGuide: "Skill setup & usage", cliTitle: "One core for the CLI and your agent.", cliDescription: "The desktop app includes srpcfg.exe; a standalone CLI is also available on Releases. Diagnostics, presets, assembly, video and map guides share the core, keeping staging separate from game deployment.", cliNote: "These examples only inspect help and module status. The skill requires explicit approval for binding conflicts and keeps staging updates separate from game deployment.", instructions: "First time here?", readme: "Read the project guide", fallback: "Browse release files" },
  footer: { description: "A configuration workspace for CS2. Clear files. Your choices.", blog: "Author's blog", project: "Source code", docs: "Guide", releases: "Releases", stack: "Built with", license: "MIT License", top: "Back to top" },
};
